### ISSUE TITLE
Quick tip

### ISSUE THREAD

**Issue by skywarth** [serkansahin4/CustomValidationLibrary#1]
Just a friendly tip:
- Don't include `.vs`. It is used for storing Visual Studio config and it is not necessary for anyone but yourself. It can also be used for malicious intentions since it contains your local dev environment.
- Don't include `bin` and `debug` folders, they are compiled exports of your program, so they don't really fit the idea of version control.

You may adjust your file/folder exclusion via `.gitignore` file.

**Comment by serkansahin4** [comment]
Thanks for your comment.
